language: node_js
node_js:
  - '8'

# a linux variant often used for running code on VM
dist: trusty
services:
  - mongodb
  - redis-server

# use a completely different set of credentials
# for dev, ci and prod (3 different files)
# multiple env vars must be set in one go
# separate entries would result in separate builds
env:
  - NODE_ENV=ci PORT=3000

# do not reinstall node_modules every time
# speed up build significantly
cache:
  directories:
    - node_modules
    - client/node_modules

# install node_modules
# package react app into client/build directory
install:
  - npm install
  - npm run build

# list a number of command to be executed
# nohup: don't kill the created process when shell exits (no hangup)
# &: take the command and run in subshell/background (Mac/Linux only)
script:
  - nohup npm run start & # travis can unpredictably kill shell, keep process alive
  - sleep 3 # server warm up
  - npm run test
